version: '3.4'

services:
  lotus:
    image: lotus
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 8226:8226
      - 8228:8228
      - 7003:7003
      - 43300:43300
